### PR TITLE
[WIP] Index page implementation

### PR DESCRIPTION
**Pull request by kbariotis**
This is the implementation of the index page.

In a nutshell:

* Implemented index page. Tested in latest Chrome, Safari, Firefox. I spotted a few issues on MS's browsers and left them for the final cross-browser testing. (Please let me know if you are going to preview this work on MS's browser and I will work on them right away.)
* Removed basscss and added a custom Bootstrap loader. Only specific Bootstrap components goes into the bundle
* Moved all html files to `pages` folder
* Left Jekyll's sass preprocessing
* Added webpack. The purpose is to pass all assets through webpack and add any appropriate process, such as css preprocessing, auto prefixing, minification, etc

Issues left:
* [x] Add the two boxes and the straight line below technologies
* [ ] Add hover state to case studies https://github.com/kbariotis/gruntwork-io.github.io/issues/7

### CODE REVIEW

**Comment by brikis98** [comment]
@kbariotis I'm excited to see this! What's the best way to run the site now? Is it possible to do it with Docker or do you have to run Jekyll/Webpack locally?

**Comment by josh-padnick** [comment]
@kbariotis I had the same issue. Ideally, I could just run:

```
docker-compose build
docker-compose up
```
...and everything would just work.

**Comment by kbariotis** [comment]
@brikis98 @josh-padnick yeah, I messed up the Docker configuration.

Please fetch the latest commits and run `docker-compose up`.

**Comment by brikis98** [comment]
Woah, this is awesome! I took a quick look at the homepage and it looks fantastic. Seems to work pretty well on mobile too!

BTW, I had to make two small tweaks to get it to run locally. Here's the output of `git diff`:

```
diff --git a/Gemfile b/Gemfile
index 68e4c2c..eabf294 100644
--- a/Gemfile
+++ b/Gemfile
@@ -1,2 +1,2 @@
 source 'https://rubygems.org'
-gem 'github-pages', '68', group: :jekyll_plugins
\ No newline at end of file
+gem 'github-pages', '127', group: :jekyll_plugins
diff --git a/docker-compose.yml b/docker-compose.yml
index bb3fc0e..283ad21 100644
--- a/docker-compose.yml
+++ b/docker-compose.yml
@@ -1,6 +1,7 @@
 web:  
-  image: gruntwork/gruntwork-io
+  build: .
+# image: gruntwork/gruntwork-io
   volumes:
     - .:/src
   ports:
-    - "4000:4000"
\ No newline at end of file
+    - "4000:4000"
```

That old version of the github-pages gem seems to have a bug, so I had to update it, and the `docker-compose.yml` change just forces the container to be built locally.

**Comment by kbariotis** [comment]
Glad you liked it @brikis98! Indeed its a very good design. I will put that diff into this branch so it goes into the master branch too.

Regarding the design, is there anything you didn't like? I think that the top illustration may need some sort of editing to be optimized for smaller mobile screens. Maybe create another version which is cut in half so the straight line goes into the center of the image. Just my 2c. Other than that I believe it's pretty good so far.

I will move on with the rest of the list I have listed above. As soon as I get your feedback I will be able to move on with the rest of the pages.

**Comment by josh-padnick** [comment]
@kbariotis Agreed that this looks great! Both the overall layout and the HTML code.

I have a few ideas for improvements, but so that we don't send you in circles, let me sync up with @brikis98 first, and we can give you a unified set of feedback.

@brikis98 Feel free to start a gdoc with desired changes, or I'll start one tomorrow.

**Comment by kbariotis** [comment]
Closing this to move on to the rest of the pages. Moving issues to separate files.

**Pull request merged**
